// @ts-check
/**
 * `hooks/dist/<name>.mjs` — the runtime floor guard, on the two paths where it speaks.
 *
 * The launcher is the file `hooks.json` names. It is generated by `esbuild.config.mjs`, it is
 * committed, and it is the first thing Codex runs for every one of the eleven registrations.
 * On the happy path it hands off to `impl/<name>.mjs` and never writes to stdout at all — so
 * the whole of its own observable behaviour is the two failure paths tested here:
 *
 *   1. **Node is older than the floor.** Codex runs a hook through `$SHELL -lc`, so the `node`
 *      a hook gets is whatever a login shell resolves, which is not necessarily the one that
 *      started Codex.
 *   2. **The impl bundle will not load.** A truncated install, a half-finished `git checkout`,
 *      a bundle from a newer plugin.
 *
 * Both paths existed to *tell the user something*, and both destroyed the message they carried
 * by writing `{"suppressOutput": true}` alongside it. Codex rejects that field at parse time on
 * `PreToolUse`, `PostToolUse` and `PermissionRequest`, and what the user sees in place of the
 * diagnostic is `• PostToolUse hook (failed)`. The failure path is exactly where the real
 * message matters most, and it was the one path with no test.
 *
 * Note what this file does **not** do: it does not grep `esbuild.config.mjs` for the string.
 * The committed bundle is what ships and what runs, so the bundle is what is staged into a
 * temp directory and executed here — with a genuinely corrupt `impl/`, and with a genuinely
 * spoofed `process.versions.node`.
 */

import test from 'node:test';
import { spawn } from 'node:child_process';
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

import {
  assert, tempDir, CODEX_ROOT, CODEX_EVENTS, assertValid, assertOutputAccepted, schemaSlug,
} from './helpers/codex-fixtures.mjs';

/** Every launcher `esbuild.config.mjs` builds — the eight registered, plus the two detached. */
const LAUNCHERS = [
  'session-start', 'prompt-recall', 'stage-prompt', 'pre-tool', 'subagent-start',
  'capture', 'checkpoint', 'session-end', 'drain', 'recall-refresh',
];

/**
 * Stage the **committed** launcher for `name` into a fresh temp directory, beside whatever
 * `impl/<name>.mjs` the caller asks for.
 *
 * @param {string} name
 * @param {string|null} impl  the impl bundle's contents, or `null` to leave it absent
 * @returns {{dir: string, script: string}}
 */
function stageLauncher(name, impl) {
  const dir = tempDir('mubit-codex-launcher-');
  const script = join(dir, `${name}.mjs`);
  copyFileSync(join(CODEX_ROOT, 'hooks', 'dist', `${name}.mjs`), script);
  if (impl !== null) {
    mkdirSync(join(dir, 'impl'), { recursive: true });
    writeFileSync(join(dir, 'impl', `${name}.mjs`), impl);
  }
  return { dir, script };
}

/**
 * Run a staged launcher for real and collect what a host would see.
 *
 * @param {string} script
 * @param {{nodeVersion?: string, dir: string}} opts
 * @returns {Promise<{code: number|null, stdout: string, stderr: string}>}
 */
async function runLauncher(script, opts) {
  const args = [];
  if (opts.nodeVersion) {
    // § The only honest way to test the floor: make the running process *report* an old
    //   version, since the launcher reads `process.versions.node` and nothing else. A test
    //   that re-implemented the comparison would be testing itself.
    const spoof = join(opts.dir, 'spoof-node-version.mjs');
    writeFileSync(spoof,
      `Object.defineProperty(process.versions, 'node', `
      + `{ value: ${JSON.stringify(opts.nodeVersion)}, configurable: true });\n`);
    args.push('--import', pathToFileURL(spoof).href);
  }
  args.push(script);

  const child = spawn(process.execPath, args, {
    stdio: ['pipe', 'pipe', 'pipe'],
    env: { PATH: process.env.PATH ?? '', HOME: opts.dir, NODE_OPTIONS: '' },
  });
  let stdout = '', stderr = '';
  child.stdout.on('data', (d) => { stdout += d; });
  child.stderr.on('data', (d) => { stderr += d; });
  child.stdin.end(JSON.stringify({ hook_event_name: 'PostToolUse' }));

  const code = await new Promise((res, rej) => {
    const t = setTimeout(() => { child.kill('SIGKILL'); rej(new Error('launcher did not exit')); }, 15000);
    child.on('close', (c) => { clearTimeout(t); res(c); });
    child.on('error', (e) => { clearTimeout(t); rej(e); });
  });
  return { code, stdout, stderr };
}

/**
 * The assertions both failure paths share: exit 0, one JSON object on stdout, and output no
 * Codex event rejects.
 *
 * @param {{code: number|null, stdout: string, stderr: string}} r
 * @param {string} what
 */
function assertHostAccepts(r, what) {
  assert.equal(r.code, 0,
    `${what} exited ${r.code}. Codex reads a non-zero exit from a hook as an error and a 2 as `
    + 'a block — a plugin that cannot start must not also stop the user working.');

  const raw = r.stdout.trim();
  assert.ok(raw, `${what} wrote nothing to stdout.`);

  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    // § Not a pedantic check. Codex injects non-JSON stdout into the model's context as
    //   developer context, so a diagnostic printed loose here is pasted into every turn.
    assert.fail(`${what} wrote stdout that is not JSON, which Codex would inject into the `
      + `model's context as developer context:\n  ${raw}\n  (${e.message})`);
  }
  assert.equal(typeof parsed, 'object');
  assert.notEqual(parsed, null);

  for (const event of CODEX_EVENTS) {
    // § Every launcher is registered on at least one event and the guard's output is the same
    //   on all of them, so the bar is: acceptable on any event it could be registered for.
    assertOutputAccepted(event, parsed, `${what} on ${event}`);
    if (event !== 'SessionEnd') {   // the one event with no output wire type at all
      assertValid(parsed, `${schemaSlug(event)}.command.output`, `${what} on ${event}`);
    }
  }
}

// ===========================================================================
// The impl-load-failure path
// ===========================================================================

test('a corrupt impl bundle produces output Codex accepts, not a rejected field', async () => {
  const { dir, script } = stageLauncher('capture', 'this is not javascript {{{\n');
  const r = await runLauncher(script, { dir });

  assertHostAccepts(r, 'the capture launcher with a corrupt impl');
  assert.match(r.stderr, /failed to load/,
    'the impl-load-failure path exists to say the install is damaged. Its stderr is the only '
    + 'place that message can appear.');
});

test('a missing impl bundle produces output Codex accepts', async () => {
  const { dir, script } = stageLauncher('capture', null);
  const r = await runLauncher(script, { dir });

  assertHostAccepts(r, 'the capture launcher with no impl at all');
  assert.match(r.stderr, /failed to load/);
});

// ===========================================================================
// The Node-floor path
// ===========================================================================

test('an old Node produces output Codex accepts, not a rejected field', async () => {
  // § The impl here is *valid*, so nothing but the floor check can account for the output.
  const { dir, script } = stageLauncher('capture', 'process.stdout.write("IMPL RAN");\n');
  const r = await runLauncher(script, { dir, nodeVersion: '18.20.8' });

  assert.doesNotMatch(r.stdout, /IMPL RAN/,
    'the floor guard let the impl load on a Node below the floor, so it is not guarding.');
  assertHostAccepts(r, 'the capture launcher on Node 18');
  assert.match(r.stderr, /requires Node >= 20/,
    'the floor path exists to name the Node version. Replacing that message with a rejected '
    + 'field is what made a real user see `PostToolUse hook (failed)` instead.');
  assert.match(r.stderr, /18\.20\.8/, 'the message should quote the version actually found');
});

test('a Node at the floor hands off to the impl', async () => {
  const { dir, script } = stageLauncher('capture', 'process.stdout.write("IMPL RAN");\n');
  const r = await runLauncher(script, { dir, nodeVersion: '20.0.0' });

  assert.match(r.stdout, /IMPL RAN/,
    'Node 20 is the floor, not one above it — package.json says `>=20.0.0`.');
});

// ===========================================================================
// Every launcher, not just the one
// ===========================================================================

test('no committed launcher writes a field Codex rejects', () => {
  for (const name of LAUNCHERS) {
    const src = readFileSync(join(CODEX_ROOT, 'hooks', 'dist', `${name}.mjs`), 'utf8');
    assert.doesNotMatch(src, /suppressOutput/,
      `hooks/dist/${name}.mjs still writes suppressOutput. It never reaches lib/hook.mjs, so `
      + 'the `forHost()` filter that fixed the impl bundles does not cover this file — it is '
      + 'generated by esbuild.config.mjs and committed as-is.');
  }
});

test('every launcher fails safe, not just capture', async () => {
  for (const name of LAUNCHERS) {
    const { dir, script } = stageLauncher(name, 'throw new Error("boom");\n');
    const r = await runLauncher(script, { dir });
    assertHostAccepts(r, `the ${name} launcher with a throwing impl`);
  }
});
